controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    # Vos autres routes ici...

    # Route de secours pour rediriger vers la page d'accueil en cas d'URL invalide
fallback_route:
    path: /{any}
    controller: App\Controller\AppController::index
    defaults:
        any: ""
    requirements:
        any: ".*"

